# Generated by Django 5.2.1 on 2025-06-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amin_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amin_icon', models.CharField(max_length=100)),
                ('amin_title', models.CharField(max_length=100)),
                ('amin_discription', models.TextField(max_length=100)),
            ],
        ),
    ]
